### ISSUE TITLE
Building project with gradle fails when building on a mac

### ISSUE THREAD

**Issue by ghost** [michel-kraemer/vertx-lang-typescript#1]
Building a project fails at 80% (`Building 80% > :run`). 
If I remove nodejs from the path, the build runs fine.

OS Version: 10.11.1 (15B42) [ El Capitan]
Nodejs version: v4.2.1
Stacktrace is:

```
./gradlew run
:compileJava UP-TO-DATE
:extractTypings UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
Oct 26, 2015 1:49:38 PM io.vertx.core.impl.DeploymentManager
SEVERE: Error: Cannot find module workflowservice.ts in <eval> at line number 141 at column number 6
javax.script.ScriptException: Error: Cannot find module workflowservice.ts in <eval> at line number 141 at column number 6
    at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
    at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
    at io.vertx.lang.js.JSVerticleFactory$JSVerticle.start(JSVerticleFactory.java:109)
    at de.undercouch.vertx.lang.typescript.TypeScriptVerticleFactory$TypeScriptVerticle.lambda$start$0(TypeScriptVerticleFactory.java:190)
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$15(ContextImpl.java:296)
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$261(OrderedExecutorFactory.java:91)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: <eval>:141:6 Error: Cannot find module workflowservice.ts
    at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)
    at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:102)
    at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:106)
    at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:110)
    at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)
    at jdk.nashorn.internal.scripts.Script$Recompilation$4$4376AAAA$\^eval\_.L:33$doRequire(.vertx/debug-js/vertx-js/util/jvm-npm.js:141)
    at jdk.nashorn.intuntime.ScriptFunctionData.invoke(ScriptFunctionData.java:648)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
    at jdk.nashorn.internal.runtime.ScriptFunction.invokeSync(ScriptFunction.java:1005)
    at jdk.nashorn.internal.scripts.Script$Recompilation$125$4168AAZ$\^eval\_.L:33$RequireNoCache(.vertx/debug-js/vertx-js/util/jvm-npm.js:124)
    at jdk.nashorn.internal.scripts.Script$124$\^eval\_.:program(<eval>:1)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:640)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
    ... 11 more

> Building 80% > :run
```

Thanks
Marco

**Comment by michel-kraemer** [comment]
Use the latest snapshot that I just uploaded here:
https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/vertx-lang-typescript/1.2.0-SNAPSHOT/
